import type { Pool } from 'mysql2/promise';

const statements = [
  `CREATE TABLE IF NOT EXISTS accounts (
    id CHAR(36) PRIMARY KEY,
    phone_hash VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS profiles (
    account_id CHAR(36) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    avatar_text VARCHAR(16) NOT NULL,
    goal_label VARCHAR(32) NOT NULL DEFAULT '',
    units VARCHAR(16) NOT NULL DEFAULT 'metric',
    age INT NULL,
    sex VARCHAR(16) NULL,
    height_cm DECIMAL(8,2) NULL,
    latest_weight_kg DECIMAL(8,2) NULL,
    target_weight_kg DECIMAL(8,2) NULL,
    goal VARCHAR(16) NULL,
    pace VARCHAR(16) NULL,
    activity VARCHAR(16) NULL,
    experience VARCHAR(16) NULL,
    training_days INT NULL,
    training_place VARCHAR(16) NULL,
    session_minutes INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_profiles_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS consents (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id CHAR(36) NOT NULL,
    scope VARCHAR(64) NOT NULL,
    granted TINYINT(1) NOT NULL,
    document_version VARCHAR(32) NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP NULL,
    consent_epoch INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_consents_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    UNIQUE KEY uq_consents_scope (account_id, scope, consent_epoch)
  )`,
  `CREATE TABLE IF NOT EXISTS goal_versions (
    id CHAR(36) PRIMARY KEY,
    account_id CHAR(36) NOT NULL,
    input_snapshot JSON NOT NULL,
    targets JSON NOT NULL,
    estimated_weeks INT NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_goal_versions_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS nutrition_plan_versions (
    id CHAR(36) PRIMARY KEY,
    account_id CHAR(36) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    effective_from_local_date DATE NULL,
    targets JSON NOT NULL,
    meal_budgets JSON NOT NULL,
    source_goal_version_id CHAR(36) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_nutrition_plan_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS foods (
    id VARCHAR(64) PRIMARY KEY,
    account_id CHAR(36) NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'custom',
    name VARCHAR(128) NOT NULL,
    detail VARCHAR(255) NOT NULL DEFAULT '',
    unit VARCHAR(32) NOT NULL,
    amount DECIMAL(12,3) NOT NULL DEFAULT 1,
    calories DECIMAL(12,2) NOT NULL DEFAULT 0,
    protein DECIMAL(12,2) NOT NULL DEFAULT 0,
    carbs DECIMAL(12,2) NOT NULL DEFAULT 0,
    fat DECIMAL(12,2) NOT NULL DEFAULT 0,
    tone VARCHAR(16) NOT NULL DEFAULT 'neutral',
    favorite TINYINT(1) NOT NULL DEFAULT 0,
    is_custom TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_foods_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS meal_entries (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id CHAR(36) NOT NULL,
    entry_id CHAR(36) NOT NULL,
    food_id VARCHAR(64) NULL,
    name VARCHAR(128) NOT NULL,
    detail VARCHAR(255) NOT NULL DEFAULT '',
    unit VARCHAR(32) NOT NULL,
    amount DECIMAL(12,3) NOT NULL DEFAULT 1,
    calories DECIMAL(12,2) NOT NULL DEFAULT 0,
    protein DECIMAL(12,2) NOT NULL DEFAULT 0,
    carbs DECIMAL(12,2) NOT NULL DEFAULT 0,
    fat DECIMAL(12,2) NOT NULL DEFAULT 0,
    tone VARCHAR(16) NOT NULL DEFAULT 'neutral',
    meal_id VARCHAR(16) NOT NULL,
    local_date DATE NOT NULL,
    time_zone_id VARCHAR(64) NOT NULL,
    utc_offset_minutes INT NOT NULL DEFAULT 0,
    occurred_at_utc DATETIME(3) NOT NULL,
    recorded_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    CONSTRAINT fk_meal_entries_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    UNIQUE KEY uq_meal_entries (account_id, entry_id)
  )`,
  `CREATE TABLE IF NOT EXISTS workout_sessions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id CHAR(36) NOT NULL,
    session_id CHAR(36) NOT NULL,
    title VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    active TINYINT(1) NOT NULL DEFAULT 0,
    completed TINYINT(1) NOT NULL DEFAULT 0,
    completed_at DATETIME(3) NULL,
    local_date DATE NOT NULL,
    template_version VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_sessions_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    UNIQUE KEY uq_workout_sessions (account_id, session_id)
  )`,
  `CREATE TABLE IF NOT EXISTS workout_sets (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workout_session_id BIGINT NOT NULL,
    set_id CHAR(36) NOT NULL,
    exercise_id VARCHAR(64) NOT NULL,
    exercise_name VARCHAR(128) NOT NULL,
    note VARCHAR(255) NOT NULL DEFAULT '',
    weight DECIMAL(12,2) NOT NULL DEFAULT 0,
    reps INT NOT NULL DEFAULT 0,
    target_reps INT NULL,
    done TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_sets_session FOREIGN KEY (workout_session_id) REFERENCES workout_sessions(id) ON DELETE CASCADE,
    UNIQUE KEY uq_workout_sets (workout_session_id, set_id)
  )`,
  `CREATE TABLE IF NOT EXISTS body_metrics (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id CHAR(36) NOT NULL,
    metric_type VARCHAR(32) NOT NULL,
    value DECIMAL(16,4) NOT NULL,
    unit VARCHAR(16) NOT NULL,
    local_date DATE NOT NULL,
    occurred_at_utc DATETIME(3) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'manual',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_body_metrics_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS backup_snapshots (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id CHAR(36) NULL,
    schema_version VARCHAR(32) NOT NULL,
    app_version VARCHAR(32) NOT NULL,
    backup_epoch INT NOT NULL DEFAULT 1,
    local_generation BIGINT NOT NULL DEFAULT 1,
    record_counts JSON NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'created',
    authoritative TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP NULL
  )`,
];

export async function ensureSchema(pool: Pool): Promise<void> {
  for (const statement of statements) {
    await pool.query(statement);
  }
}
